openapi: 3.0.3
info:
  title: sample API
  version: 1.0.0

paths:
  /free:
    get:
      description: query free form dictionary
      responses:
        '200':
          description: dictionary response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Free'

  /values:
    get:
      description: query object dictionary
      responses:
        '200':
          description: dictionary response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Values'

  /multi-values:
    get:
      description: query object dictionary
      responses:
        '200':
          description: dictionary response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiValues'

components:
  schemas:

    Free:
      description: key is string, value is anything
      type: object
      additionalProperties: { }

    Values:
      description: key is string, value is a Value object
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Value'

    MultiValues:
      description: key is string, value is a Value array
      type: object
      additionalProperties:
        type: array
        items:
          $ref: '#/components/schemas/Value'

    Value:
      type: object
      properties:
        text:
          type: string
